name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: main

    env:
      FRESH_ENV: ${{ vars.PRD_FRESH_ENV }}
      STRIPE_SECRET_KEY: ${{ secrets.PRD_STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.PRD_STRIPE_WEBHOOK_SECRET }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.PRD_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRD_SUPABASE_DB_PASSWORD }}
      SUPABASE_JWT_SECRET: ${{ secrets.PRD_SUPABASE_JWT_SECRET }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRD_SUPABASE_PROJECT_ID }}
      VERBOSE: ${{ vars.PRD_VERBOSE }}
      WEB_APP_URL: ${{ secrets.PRD_WEB_APP_URL }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Set Environment Variable Secrets
        run: |
          supabase secrets set FRESH_ENV=$FRESH_ENV
          supabase secrets set STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
          supabase secrets set STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
          supabase secrets set VERBOSE=$VERBOSE
          supabase secrets set WEB_APP_URL=$WEB_APP_URL

      - name: Migrate Database
        run: supabase db push

      - name: Deploy Stripe Function
        run: supabase functions deploy --no-verify-jwt stripe

      - name: Deploy Users Function
        run: supabase functions deploy users
